POST http://localhost:3001/api/v1/auth/signup
Content-Type: application/json

{
  
  
  "email": "muhammadhussnainasghar866@gmail.com",
  "phoneNumber": "0302144551712",
  "password": "Szhms5starsz!",
  "userName" : "Shah hussain"
}
