import { z } from "zod";
import mongoose from 'mongoose';

// Custom validation for MongoDB ObjectId strings
const objectIdSchema = z.string().refine(
  (val) => mongoose.Types.ObjectId.isValid(val),
  {
    message: "Invalid ObjectId format",
  }
);

export const variantSchema = z.object({
  size: z.string().min(1, "Size is required.").optional(), // Made optional
  color: z.string().min(1, "Color is required.").optional(), // Made optional
  price: z.number().min(0, "Price cannot be negative."),
  stock: z.number().int().min(0, "Stock cannot be negative."),
  _id: objectIdSchema.optional(), // _id is generated by MongoDB, optional for creation
});

// Custom URL validation to allow both absolute and relative paths
const imageUrlSchema = z.string().refine(
  (val) => {
    // Check if it's an absolute URL or a relative path starting with '/'
    return val.startsWith('http://') || val.startsWith('https://') || val.startsWith('/');
  },
  {
    message: "Must be a valid URL or a relative path (e.g., /image.jpg).",
  }
);

export const createProductSchema = z.object({
  name: z.string().min(3, "Product name is required and must be at least 3 characters."),
  description: z.string().min(10, "Product description is required and must be at least 10 characters."),
  category: z.string().min(1, "Category is required."),
  imageUrls: z.array(imageUrlSchema)
    .min(1, "At least one image URL is required.") // Enforce minimum 1 image
    .max(5, "Maximum of 5 images allowed."), // Enforce maximum 5 images
  isFeatured: z.boolean().default(false),
  variants: z.array(variantSchema).optional(), // Made optional
}).strict();

export const updateProductSchema = z.object({
  name: z.string().min(3, "Product name must be at least 3 characters.").optional(),
  description: z.string().min(10, "Product description must be at least 10 characters.").optional(),
  category: z.string().min(1, "Category is required.").optional(),
  imageUrls: z.array(imageUrlSchema)
    .max(5, "Maximum of 5 images allowed.") // Enforce maximum 5 images for updates
    .optional(), // Still optional for updates, as you might not update images every time
  isFeatured: z.boolean().optional(),
  variants: z.array(variantSchema).optional(), // Made optional
}).partial(); // Allow partial updates